using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartnerFlowAPI.Database.Entities;
using PartnerFlowAPI.Database.Enums;



namespace PartnerFlowAPI.Database.Configuration
{
    public class AppTblPF_DocumentRequiredConfiguration : IEntityTypeConfiguration<AppTblPF_DocumentRequired>
    {
        public void Configure(EntityTypeBuilder<AppTblPF_DocumentRequired> entity)
        {
            entity.ToTable("tblPF_DocumentRequired");

            entity.HasQueryFilter(e => e.BitIsDeleted == false && e.dtDeletedDate == null);
            entity.HasKey(e => e.IntPFDocumentRequiredID);

            entity.Property(e => e.IntAssureType)
            .HasConversion(new EnumToNumberConverter<AssureType, int>())
            .HasColumnType("int");

            entity.Property(e => e.VcApplicationNumber).HasColumnType("nvarchar")
                .HasMaxLength(200);

            entity.Property(e => e.IntDocumentTypeID).HasColumnType("int");

            entity.Property(e => e.VcDocumentFileName).HasColumnType("nvarchar")
                .HasMaxLength(510)
                .IsRequired(false);

            entity.Property(e => e.VcDocumentFileType).HasColumnType("nvarchar")
                .HasMaxLength(200)
                .IsRequired(false);

            entity.Property(e => e.VcDocumentComment)
            .HasColumnType("nvarchar")
                .HasMaxLength(510)
                .IsRequired(false);

            entity.Property(e => e.IntStatus).HasColumnType("int");
            entity.Property(e => e.IntRow).HasColumnType("int");

            entity.Property(e => e.vcDMSFilePath)
            .HasColumnType("nvarchar(1000)")
            .IsRequired(false);

            entity.Property(e => e.vcBlobFilePath)
            .HasColumnType("nvarchar(1000)")
            .IsRequired(false);

            entity.Property(e => e.vcRequirementComment)
            .HasColumnType("nvarchar(200)")
            .IsRequired(false);

            entity.Property(e => e.vcUWFollowupCode)
            .HasColumnType("nvarchar(50)")
            .IsRequired(false);

            entity.Property(e => e.vcAutoDocumentType)
            .HasColumnType("nvarchar(50)")
            .IsRequired(false);

            entity.Property(e => e.btAutoGenrated)
        .HasColumnType("bit");

            entity.Property(e => e.dtAutoGeneratedOn)
      .HasColumnType("datetime2(7)")
      .IsRequired(false);

            entity.Property(e => e.btResubmit)
        .HasColumnType("bit").HasDefaultValue(false);

            entity.Property(e => e.IntPHRequirementID).HasColumnName("intPHRequirementID");
            entity.Property(e => e.intUWRequirementID).HasColumnName("intUWRequirementID");

            entity.Property(e => e.btIsForEditApp)
              .HasColumnType("bit")
              .IsRequired(false);
        }
    }
}
