using PartnerFlowAPI.Database.Common;
using PartnerFlowAPI.Database.Enums;


namespace PartnerFlowAPI.Database.Entities
{
    public class AppTblPF_DocumentRequired : AuditEntity
    {
        public int IntPFDocumentRequiredID { get; set; }
        public AssureType IntAssureType { get; set; }
        public string? VcApplicationNumber { get; set; }
        public int IntDocumentTypeID { get; set; }
        public int? IntSubTypeID { get; set; }
        public string? VcDocumentFileName { get; set; }
        public string? VcDocumentFileType { get; set; }
        public string? VcDocumentComment { get; set; }
        public int IntStatus { get; set; }
        public string? vcDMSFilePath { get; set; }
        public string? vcDMSIdexNo { get; set; }
        public DateTime? dtDMSDate { get; set; }
        public string? vcAutoDocumentType { get; set; }
        public string? vcBlobFilePath { get; set; }
        public bool btAutoGenrated { get; set; }
        public DateTime? dtAutoGeneratedOn { get; set; }
        public int IntRow { get; set; }
        public bool? btResubmit { get; set; }
        public int? IntPHRequirementID { get; set; }
        public string? vcRequirementComment { get; set; }
        public int? intResubmissionStatus { get; set; }
        public int? intUWRequirementID { get; set; }
        public string? vcUWFollowupCode { get; set; }
        public bool? btIsForEditApp { get; set; }
    }
}
