using FGLI_SharedLibrary.Abstractions;
using FGLI_SharedLibrary.Core.Common.Utilities;
using MediatR;
using Microsoft.EntityFrameworkCore;
using ProposalFormService.Domain.Entities.Document;
using ProposalFormService.Domain.Enums;
using ProposalFromService.Application.Configuration.Data;

namespace ProposalFromService.Application.Features.DocumentRequired.Command
{
    public class AddDocymentToApplicationCommand : IRequest<string>
    {
        public string ApplicationNumber { get; set; }
        public AssureType AssureType { get; set; } = AssureType.LA;
        public string DocumentType { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public int DocumnetTypeId { get; set; }
        public int? DocumnetSubTypeId { get; set; }
        public string DocumentFileType { get; set; }
        public int IntStatus { get; set; } = 0;
        public bool AutoGen { get; set; } = false;
        public int IntRow { get; set; } = 1;
        public int DocumentrequiredId { get; set; }
        public class AddDocymentToApplicationCommandHandler : IRequestHandler<AddDocymentToApplicationCommand, string>
        {

            private readonly IApplicationDbContext _context;
            private readonly IDateTimeService _dateTimeService;
            public AddDocymentToApplicationCommandHandler(IApplicationDbContext context, IDateTimeService dateTimeService)
            {
                _context = context;
                _dateTimeService = dateTimeService;
            }

            public async Task<string> Handle(AddDocymentToApplicationCommand request, CancellationToken cancellationToken)
            {
                DeleteDocumentCommand doc = new DeleteDocumentCommand();
                AppTblPF_DocumentRequired entity = new AppTblPF_DocumentRequired();
                string status = "";
                if (request.IntRow == 1)
                {
                    entity = new AppTblPF_DocumentRequired
                    {
                        IntAssureType = request.AssureType,
                        VcApplicationNumber = request.ApplicationNumber,
                        IntDocumentTypeID = request.DocumnetTypeId,
                        IntSubTypeID = request.DocumnetSubTypeId,
                        VcDocumentFileName = request.FileName,
                        VcDocumentFileType = request.DocumentFileType,
                        VcDocumentComment = null,
                        vcAutoDocumentType = request.DocumentType,
                        vcBlobFilePath = request.FileUrl,
                        btAutoGenrated = request.AutoGen,
                        dtAutoGeneratedOn = _dateTimeService.Now,
                        IntRow = 1,
                        btResubmit = false,
                        IntStatus = request.IntStatus,
                        intResubmissionStatus = 0
                    };
                    _context.AppTblPF_DocumentRequired.Add(entity);
                    status = "Document Added";
                }
                else
                {
                    entity.BitIsDeleted = true;
                    entity.dtDeletedDate = _dateTimeService.Now;

                    List<AppTblPF_DocumentRequired>? ShiftRowentity = await _context.AppTblPF_DocumentRequired
                                                    .Where(c => c.IntPFDocumentRequiredID == request.DocumentrequiredId)
                                                    .ToListAsync();
                    if (Guard.IsListNotNull(ShiftRowentity))
                    {
                        foreach (AppTblPF_DocumentRequired item in ShiftRowentity)
                        {
                            item.IntRow = item.IntRow - 1;
                        }
                    }
                    status = "Document Deleted";
                }



                await _context.SaveChangesAsync(cancellationToken);
                return status;
            }
        }
    }
}
